import path from 'node:path';import {inflateRawSync} from 'node:zlib';import {FileMetadata,Finding} from './models.js';import {sha256} from './evidence-builder.js';import {loadPolicy} from './config.js';import {normalizeFilename,links} from './metadata-extractor.js';
export const DOCUMENT_PARSE_FAILED='DOCUMENT_PARSE_FAILED';
export async function analyzeFile(buf:Buffer,filename:string,mime:string):Promise<{text:string;metadata:FileMetadata;findings:Finding[];errorCode?:string}>{const p=loadPolicy();const normalizedName=normalizeFilename(filename);const extension=path.extname(normalizedName).toLowerCase();const meta:FileMetadata={originalName:filename,normalizedName,extension,mimeType:mime,size:buf.length,sha256:sha256(buf),extractedTextLength:0,encrypted:false,parseSuccess:false,externalLinks:[]};const findings:Finding[]=[];if(buf.length>p.limits.maxFileBytes)findings.push(fileFinding('file_size_limit_exceeded'));if(!p.supportedFiles[extension])findings.push(fileFinding('unsupported_file_type'));else if(!p.supportedFiles[extension].includes(mime))findings.push(fileFinding('mime_extension_mismatch'));if(findings.length)return{text:'',metadata:meta,findings};try{let text='';if(extension==='.txt')text=buf.toString('utf8');else if(extension==='.docx')text=extractDocxText(buf);else if(extension==='.pdf'){const parsed=extractPdfText(buf);text=parsed.text;meta.pageCount=parsed.pageCount;meta.title=parsed.title;meta.author=parsed.author}meta.parseSuccess=true;meta.documentLength=text.length;meta.extractedTextLength=text.length;meta.externalLinks=links(text);return{text,metadata:meta,findings}}catch{meta.encrypted=true;findings.push(fileFinding('document_parse_failed'));return{text:'',metadata:meta,findings,errorCode:DOCUMENT_PARSE_FAILED}}}
function fileFinding(type:string):Finding{return{category:'FILE_SAFETY',severity:type==='document_parse_failed'?'HIGH':'MEDIUM',type,matchedRule:type,evidence:type,location:{source:'file_metadata',start:0,end:0},confidence:0.95}}
function extractPdfText(buf:Buffer){if(buf.subarray(0,8).toString('latin1').indexOf('%PDF-')!==0)throw new Error('not_pdf');const src=buf.toString('latin1');const title=pdfInfo(src,'Title');const author=pdfInfo(src,'Author');const pageCount=Math.max(1,(src.match(/\/Type\s*\/Page\b/g)||[]).length);const texts:string[]=[];const streamRe=/<<(.*?)>>\s*stream\r?\n([\s\S]*?)\r?\nendstream/g;let m:RegExpExecArray|null;while((m=streamRe.exec(src))){let data=Buffer.from(m[2],'latin1');if(/\/FlateDecode\b/.test(m[1]))data=inflateRawSync(data);texts.push(...extractPdfStringLiterals(data.toString('latin1')))}if(!texts.join('').trim())throw new Error('empty_pdf_text');return{text:texts.join(' ').replace(/\s+/g,' ').trim(),pageCount,title,author}}
function pdfInfo(src:string,key:string){const m=new RegExp(`/${key}\\s*\\(([^)]*)\\)`).exec(src);return m?decodePdfLiteral(m[1]):undefined}
function extractPdfStringLiterals(s:string){const out:string[]=[];const re=/\((?:\\.|[^\\)])*\)\s*(?:Tj|'|")|\[((?:\s*\((?:\\.|[^\\)])*\)\s*)+)\]\s*TJ/g;let m:RegExpExecArray|null;while((m=re.exec(s))){const chunk=m[1]??m[0];const lits=chunk.match(/\((?:\\.|[^\\)])*\)/g)||[];for(const lit of lits)out.push(decodePdfLiteral(lit.slice(1,-1))) }return out}
function decodePdfLiteral(s:string){const escapes:Record<string,string>={n:'\n',r:'\r',t:'\t',b:'\b',f:'\f','(':'(',')':')','\\':'\\'};return s.replace(/\\([nrtbf()\\])/g,(_,c:string)=>escapes[c]||c).replace(/\\([0-7]{1,3})/g,(_,o:string)=>String.fromCharCode(parseInt(o,8)))}
function extractDocxText(buf:Buffer){if(buf.subarray(0,2).toString('latin1')!=='PK')throw new Error('not_docx');const xml=readZipEntry(buf,'word/document.xml');if(!xml)throw new Error('missing_document_xml');return xml.replace(/<w:tab\/>/g,'\t').replace(/<w:br\/>/g,'\n').replace(/<[^>]+>/g,' ').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&amp;/g,'&').replace(/\s+/g,' ').trim()}
function readZipEntry(buf:Buffer,name:string){let off=0;while(off<buf.length-30){if(buf.readUInt32LE(off)!==0x04034b50){off++;continue}const method=buf.readUInt16LE(off+8),csize=buf.readUInt32LE(off+18),nlen=buf.readUInt16LE(off+26),elen=buf.readUInt16LE(off+28);const fname=buf.subarray(off+30,off+30+nlen).toString('utf8');const start=off+30+nlen+elen;const data=buf.subarray(start,start+csize);if(fname===name){if(method===0)return data.toString('utf8');if(method===8)return inflateRawSync(data).toString('utf8');throw new Error('unsupported_zip_compression')}off=start+csize}return undefined}
