import {Finding} from '../models.js';import {add} from './utils.js';
const publicReason='공개 블록체인 주소는 비밀 키가 아닙니다.';
const publicTypes=new Set(['XRPL_PUBLIC_ADDRESS','ETHEREUM_PUBLIC_ADDRESS','BITCOIN_PUBLIC_ADDRESS']);
function overlapsSecret(m:{start:number;end:number},secrets:{start:number;end:number}[]){return secrets.some(s=>m.start<s.end&&m.end>s.start)}
export function detectFinancialData(text:string,source='prompt'){const out:Finding[]=[];const secrets:{start:number;end:number}[]=[];const specs:[string,RegExp,number][]=[['IBAN',/\b[A-Z]{2}\d{2}[A-Z0-9]{11,30}\b/g,.78],['SWIFT_BIC',/\b[A-Z]{6}[A-Z0-9]{2}(?:[A-Z0-9]{3})?\b/g,.72],['US_ROUTING_NUMBER_CANDIDATE',/\brouting\s*(?:number)?\s*[:=]?\s*\d{9}\b/gi,.55],['BLOCKCHAIN_PRIVATE_KEY',/\b(?:private key|wallet private)\s*[:=]\s*(?:0x)?[a-fA-F0-9]{64}\b/gi,.94],['EXCHANGE_API_KEY',/\b(?:binance|upbit|bithumb|coinbase)[-_ ]?(?:api)?[-_ ]?key\s*[:=]\s*[A-Za-z0-9_-]{16,}\b/gi,.85],['CUSTOMER_NUMBER',/(?:고객번호|고객\s*ID|customer\s*(?:no|number|id)|계약번호|contract\s*(?:no|number))\s*[:=]?\s*[A-Za-z0-9-]{4,}\b/gi,.72],['CARD_EXPIRY',/\b(?:0[1-9]|1[0-2])\/(?:2[6-9]|3[0-9])\b/g,.75],['CARD_CVV',/\bcvv\s*[:=]?\s*\d{3,4}\b/gi,.72]];
for(const[s,re,c]of specs)for(const m of text.matchAll(re)){const start=m.index!;if(s==='BLOCKCHAIN_PRIVATE_KEY')secrets.push({start,end:start+m[0].length});add(out,s,s.includes('PRIVATE')?'CRYPTO_SECRET':s==='CUSTOMER_NUMBER'?'CUSTOMER_DATA':'FINANCIAL_DATA',s.includes('PRIVATE')?'CRITICAL':s==='CUSTOMER_NUMBER'?'MEDIUM':'MEDIUM',c,m[0],start,source,'financial_'+s.toLowerCase(),{decisionContribution:s.includes('PRIVATE')?'BLOCK':s==='CUSTOMER_NUMBER'?'REVIEW':'REVIEW',maskingRequired:s.includes('PRIVATE')} as any)}
for(const m of text.matchAll(/(?:AML|의심거래|조사대상|내부\s*사건번호|case\s*#?\s*[A-Za-z0-9-]+)/gi))add(out,'INVESTIGATION_CONTEXT','RISK_CONTEXT','MEDIUM',.72,m[0],m.index!,source,'investigation_context',{decisionContribution:'NONE' as any,maskingRequired:false} as any);
for(const m of text.matchAll(/(?:송금(?:해|하라|하세요)|전송(?:해|하라|하세요)|transfer\s+(?:funds|asset|crypto)|send\s+(?:funds|asset|crypto))/gi))add(out,'ASSET_TRANSFER_INTENT','RISK_CONTEXT','MEDIUM',.68,m[0],m.index!,source,'asset_transfer_intent',{decisionContribution:'NONE' as any,maskingRequired:false} as any)
const pubs:[string,RegExp,number,string][]=[['ETHEREUM_PUBLIC_ADDRESS',/\b0x[a-fA-F0-9]{40}\b/g,.98,'Ethereum public address'],['BITCOIN_PUBLIC_ADDRESS',/\b(?:bc1[ac-hj-np-z02-9]{11,71}|[13][a-km-zA-HJ-NP-Z1-9]{25,34})\b/g,.94,'Bitcoin public address'],['XRPL_PUBLIC_ADDRESS',/\br[1-9A-HJ-NP-Za-km-z]{25,35}\b/g,.98,'XRPL public address']];
for(const[s,re,c,rule]of pubs)for(const m of text.matchAll(re)){const start=m.index!,end=start+m[0].length;if(overlapsSecret({start,end},secrets))continue;add(out,s,'PUBLIC_IDENTIFIER','LOW',c,m[0],start,source,rule,{decisionContribution:'NONE' as any,maskingRequired:false,reason:publicReason,maskedValue:m[0]})}
return out}
export const PUBLIC_BLOCKCHAIN_ADDRESS_TYPES=publicTypes;
