import test from 'node:test';import assert from 'node:assert/strict';import {analyzeFile} from '../src/file-analyzer.js';import {detectSensitiveData} from '../src/sensitive-data-detector.js';import {maskText} from '../src/masking-engine.js';import {evaluatePolicy} from '../src/policy-engine.js';import {buildServer} from '../src/server.js';import {listAudit,resetAudit} from '../src/audit-log.js';
const pdfBinaryTokens=['%PDF-','FlateDecode','stream'];
test('normal PDF extracts readable body without PDF structure tokens',async()=>{const pdf=makePdf('Contact hong@example.com or 010-1234-5678 for approval.');const analyzed=await analyzeFile(pdf,'contact.pdf','application/pdf');assert.equal(analyzed.metadata.parseSuccess,true);assert.match(analyzed.text,/Contact hong@example.com/);for(const token of pdfBinaryTokens)assert.equal(analyzed.text.includes(token),false)});
test('PDF email and phone are detected and masked',async()=>{const analyzed=await analyzeFile(makePdf('Email hong@example.com phone 010-1234-5678'),'contact.pdf','application/pdf');const findings=detectSensitiveData(analyzed.text,'file_body');assert.ok(findings.some(f=>f.type==='EMAIL'));assert.ok(findings.some(f=>f.type==='PHONE'));const masked=maskText(analyzed.text,findings);assert.equal(masked.safeText.includes('hong@example.com'),false);assert.equal(masked.safeText.includes('010-1234-5678'),false)});
test('unparseable PDF is REVIEW instead of ALLOW',async()=>{const analyzed=await analyzeFile(Buffer.from('%PDF-1.7\n1 0 obj <<>> endobj\n%%EOF','latin1'),'broken.pdf','application/pdf');assert.equal(analyzed.errorCode,'DOCUMENT_PARSE_FAILED');assert.equal(analyzed.text,'');assert.equal(evaluatePolicy(analyzed.findings).decision,'REVIEW')});
test('PDF binary is excluded from API response and audit log',async()=>{resetAudit();const app=buildServer();const boundary='----agentguardtest';const pdf=makePdf('Email hong@example.com phone 010-1234-5678');const body=Buffer.concat([Buffer.from(`--${boundary}\r\nContent-Disposition: form-data; name="file"; filename="contact.pdf"\r\nContent-Type: application/pdf\r\n\r\n`,'latin1'),pdf,Buffer.from(`\r\n--${boundary}--\r\n`,'latin1')]);const res=await app.inject({method:'POST',url:'/files/inspect',headers:{'content-type':`multipart/form-data; boundary=${boundary}`},payload:body});assert.equal(res.statusCode,200);const payload=res.body;const audit=JSON.stringify(listAudit());for(const token of pdfBinaryTokens){assert.equal(payload.includes(token),false);assert.equal(audit.includes(token),false)}await app.close()});
test('DOCX and TXT handling remains supported',async()=>{const txt=await analyzeFile(Buffer.from('hello hong@example.com','utf8'),'a.txt','text/plain');assert.equal(txt.text,'hello hong@example.com');const docx=await analyzeFile(makeDocx('docx hello hong@example.com'),'a.docx','application/vnd.openxmlformats-officedocument.wordprocessingml.document');assert.equal(docx.metadata.parseSuccess,true);assert.match(docx.text,/docx hello hong@example.com/)});
function makePdf(text:string){const stream=`BT /F1 12 Tf 72 720 Td (${escapePdf(text)}) Tj ET`;return Buffer.from(`%PDF-1.7\n1 0 obj << /Type /Catalog /Pages 2 0 R >> endobj\n2 0 obj << /Type /Pages /Count 1 /Kids [3 0 R] >> endobj\n3 0 obj << /Type /Page /Parent 2 0 R /Contents 4 0 R >> endobj\n4 0 obj << /Length ${stream.length} >>\nstream\n${stream}\nendstream\nendobj\n%%EOF`,'latin1')}
function escapePdf(s:string){return s.replace(/[\\()]/g,'\\$&')}
function makeDocx(text:string){const xml=`<?xml version="1.0" encoding="UTF-8"?><w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body><w:p><w:r><w:t>${text}</w:t></w:r></w:p></w:body></w:document>`;return zipStored('word/document.xml',Buffer.from(xml,'utf8'))}
function zipStored(name:string,data:Buffer){const n=Buffer.from(name);const local=Buffer.alloc(30);local.writeUInt32LE(0x04034b50,0);local.writeUInt16LE(20,4);local.writeUInt16LE(0,6);local.writeUInt16LE(0,8);local.writeUInt32LE(0,10);local.writeUInt32LE(0,14);local.writeUInt32LE(data.length,18);local.writeUInt32LE(data.length,22);local.writeUInt16LE(n.length,26);local.writeUInt16LE(0,28);return Buffer.concat([local,n,data])}
